name: multilabel_classification
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tqdm=4.67.1
  - numpy=2.0.2
  - nbconvert=7.16.6
  - scikit-learn==1.7.2
  - pip:
    - torchvision==0.24.0
    - torch --index-url https://download.pytorch.org/whl/cu130
