name: semantic_changes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter=1.1.1
  - numpy=2.3.5
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - tqdm=4.67.1
  - nbconvert=7.16.6
  - matplotlib=3.10.7