name: szept_czy_krzyk
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.2.3
  - scikit-learn=1.6.1
  - xgboost=2.1.4
  - pandas=2.2.3
  - matplotlib=3.10.0
  - nbconvert=7.16.6
  - jupyter
  - pillow==10.2.0
  - tqdm==4.67.1
  - seaborn==0.13.2
  - librosa==0.11.0
  - pip:
    - torch==2.9.1 --index-url https://download.pytorch.org/whl/cu130
    - torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cu130